FROM node:alpine
WORKDIR /app
COPY package.json .
RUN npm install
# Pas besoin de copier . . car on utilise un bind mount dans le docker-compose.dev.yml
# COPY . .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
