version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.env
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 5173:5173
